# Generated by Django 6.1 on 2026-09-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_serie_curso'),
        ('usuario', '0002_alter_aluno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='disciplinas_escolhidas',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='sistema.disciplina'),
        ),
    ]
