# Generated by Django 6.1 on 2026-08-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='cursos', to='sistema.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('bimestre', models.CharField(choices=[('1', 'Primeiro'), ('2', 'Segundo'), ('3', 'Terceiro'), ('4', 'Quarto')], max_length=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='sistema.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano')])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='sistema.curso')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaTecnico',
            fields=[
                ('disciplina_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sistema.disciplina')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_tecnicas', to='sistema.curso')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_tecnicas', to='sistema.serie')),
            ],
            bases=('sistema.disciplina',),
        ),
    ]
