# Generated by Django 6.1 on 2026-08-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano')], unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='sistema.disciplina'),
        ),
    ]
