# Generated by Django 6.1 on 2026-08-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_disciplinatecnico_serie'),
        ('sistema', '0002_serie_alter_curso_disciplinas'),
    ]

    operations = [
    ]
