# Generated by Django 6.1 on 2026-09-03 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_merge_20260828_0932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinatecnico',
            name='serie',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='sistema.serie'),
        ),

        migrations.AlterField(
            model_name='serie',
            name='ano',
            field=models.PositiveSmallIntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano')]),
        ),
    ]
