# Generated by Django 6.1 on 2026-09-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_remove_disciplinatecnico_serie_disciplina_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='sistema.curso'),
        ),
    ]
